-- Run this in Supabase SQL Editor
-- Products that already exist will be skipped

INSERT INTO ph_products (name, domain, slug, category) VALUES
  ('Welltory', 'welltory.com', 'welltory-2', 'Product Hunt'),
  ('CyberCut AI', 'cybercut.ai', 'cybercut-ai', 'Product Hunt'),
  ('Incredible', 'incredible.one', 'incredible-2', 'Product Hunt'),
  ('ClickUp 4.0', 'clickup.com', 'clickup-4-0', 'Product Hunt'),
  ('SnapTodo', 'snaptodo.app', 'snaptodo', 'Product Hunt'),
  ('Google Nano Banana Pro', 'deepmind.google', 'google-nano-banana-pro', 'Product Hunt'),
  ('Documentation.AI', 'documentation.ai', 'documentation-ai', 'Product Hunt'),
  ('Claude Opus 4.5', 'anthropic.com', 'claude-opus-4-5', 'Product Hunt'),
  ('Paraflow ', 'paraflow.com', 'paraflow', 'Product Hunt'),
  ('Markopolo AI', 'markopolo.ai', 'markopolo-ai-2', 'Product Hunt'),
  ('MultiDrive', 'multidrive.io', 'multidrive', 'Product Hunt'),
  ('Hatable', 'hatable.art', 'hatable', 'Product Hunt'),
  ('Raycast for Windows', 'raycast.com', 'raycast-for-windows', 'Product Hunt'),
  ('Taskade Genesis', 'taskade.com', 'taskade-genesis', 'Product Hunt'),
  ('Questas', 'questas.co', 'questas', 'Product Hunt'),
  ('Lila by Zivy', 'lila.zivy.app', 'lila-by-zivy-2', 'Product Hunt'),
  ('Gemini Deep Research Agent', 'ai.google.dev', 'gemini-deep-research-agent', 'Product Hunt'),
  ('Stickerbox', 'stickerbox.com', 'stickerbox', 'Product Hunt'),
  ('GNGM', 'gngm.app', 'gngm', 'Product Hunt'),
  ('Dimension', 'dimension.dev', 'dimension-3', 'Product Hunt'),
  ('SciSpace BioMed Agent ', 'scispace.com', 'scispace-biomed-agent', 'Product Hunt'),
  ('Finesse by Skippr AI', 'skippr.ai', 'finesse-by-skippr-ai', 'Product Hunt'),
  ('Agenta', 'agenta.ai', 'agenta', 'Product Hunt'),
  ('Ramble by Todoist', 'todoist.com', 'ramble-by-todoist', 'Product Hunt'),
  ('Qoder JetBrains Plugin', 'qoder.com', 'qoder-jetbrains-plugin-2', 'Product Hunt'),
  ('Anytype Chats', 'chats.anytype.io', 'anytype-chats', 'Product Hunt'),
  ('Juno digital planner', 'juno.do', 'juno-digital-planner', 'Product Hunt'),
  ('MyLens for Youtube ', 'mylens.ai', 'mylens-for-youtube', 'Product Hunt'),
  ('Rubber Duck', 'tryrubberduck.com', 'rubber-duck', 'Product Hunt'),
  ('plok.sh', 'plok.sh', 'plok-sh', 'Product Hunt'),
  ('TwelveLabs Marengo 3.0', 'twelvelabs.io', 'twelvelabs-marengo-3-0', 'Product Hunt'),
  ('Walk Mate', 'walk-mate.app', 'walk-mate', 'Product Hunt'),
  ('Kaily ', 'kaily.ai', 'kaily', 'Product Hunt'),
  ('Koyal', 'beta.koyal.ai', 'koyal', 'Product Hunt'),
  ('Audience Loop', 'aloop.icustomer.ai', 'audience-loop', 'Product Hunt'),
  ('Bun', 'bun.com', 'bun', 'Product Hunt'),
  ('Snippets AI', 'getsnippets.ai', 'snippets-ai', 'Product Hunt'),
  ('TrueFoundry AI Gateway', 'truefoundry.com', 'truefoundry-ai-gateway', 'Product Hunt'),
  ('Browser Cash', 'browser.cash', 'browser-cash', 'Product Hunt'),
  ('Hero Widget', 'herowidget.com', 'hero-widget', 'Product Hunt'),
  ('Gedd.it', 'gedd.it', 'gedd-it', 'Product Hunt'),
  ('BrandJet AI', 'brandjet.ai', 'brandjet-ai', 'Product Hunt'),
  ('2pr v.2.0', '2pr.io', '2pr-v-2-0', 'Product Hunt'),
  ('Felo', 'felo.ai', 'felo-2', 'Product Hunt'),
  ('SimRepo', 'github.com', 'simrepo', 'Product Hunt'),
  ('Cocoon by Telegram', 'cocoon.org', 'cocoon-by-telegram', 'Product Hunt'),
  ('delight.ai', 'delight.ai', 'delight-ai', 'Product Hunt'),
  ('Korgi', 'korgiboard.com', 'korgi', 'Product Hunt'),
  ('Strater AI', 'strater.in', 'strater-ai', 'Product Hunt'),
  ('Vybe', 'vybe.build', 'vybe-2df39e76-cce1-4f8b-9278-3c7c003929df', 'Product Hunt'),
  ('Google Workspace Studio', 'workspace.google.com', 'google-workspace-studio', 'Product Hunt'),
  ('CatDoes v3', 'catdoes.com', 'catdoes-v3-2', 'Product Hunt'),
  ('Protaigé', 'protaige.com', 'protaige', 'Product Hunt'),
  ('Checkit', 'getcheck.it', 'checkit-2', 'Product Hunt'),
  ('Email Buttons', 'emailbuttons.com', 'email-buttons', 'Product Hunt'),
  ('Addsubtitle', 'addsubtitle.ai', 'addsubtitle-4', 'Product Hunt'),
  ('Planndu ', 'apps.apple.com', 'planndu-bdd9f545-e32a-4e2d-99d0-fdad81e02344', 'Product Hunt'),
  ('Rumi.ai', 'rumi.ai', 'rumi-ai', 'Product Hunt'),
  ('Runway Gen-4.5', 'runwayml.com', 'runway-gen-4-5', 'Product Hunt'),
  ('Artifacts', 'artifacts.is', 'artifacts', 'Product Hunt'),
  ('Orion 1.0', 'blog.kagi.com', 'orion-1-0', 'Product Hunt'),
  ('Yolk', 'yolk.coach', 'yolk-2', 'Product Hunt'),
  ('Browser Use Skills', 'browser-use.com', 'browser-use-skills', 'Product Hunt'),
  ('Dex by Thirdlayer', 'joindex.com', 'dex-by-thirdlayer', 'Product Hunt'),
  ('Signal by Vouch', 'vouchfor.com', 'signal-by-vouch', 'Product Hunt'),
  ('Suprr', 'suprr.app', 'suprr-2', 'Product Hunt'),
  ('Macaly 3.0', 'macaly.com', 'macaly-3-0', 'Product Hunt'),
  ('ProspectEcho', 'prospectecho.com', 'prospectecho', 'Product Hunt'),
  ('Hyvor Post', 'post.hyvor.com', 'hyvor-post-2', 'Product Hunt'),
  ('Gemini 3 Brand Audit', 'gemini3audit.com', 'gemini-3-brand-audit', 'Product Hunt'),
  ('RightNow', 'rightnowai.co', 'rightnow', 'Product Hunt'),
  ('Gubb.net', 'gubb.net', 'gubb-net', 'Product Hunt'),
  ('Momotaro', 'momotaro.app', 'momotaro', 'Product Hunt'),
  ('Unosend', 'unosend.co', 'unosend', 'Product Hunt'),
  ('Inference Engine by GMI Cloud', 'gmicloud.ai', 'inference-engine-by-gmi-cloud-2', 'Product Hunt'),
  ('RingIt', 'ringit.app', 'ringit', 'Product Hunt'),
  ('Kortex', 'yaksh1.github.io', 'kortex-3', 'Product Hunt'),
  ('Music Videos by Mozart', 'mozartai.com', 'music-videos-by-mozart', 'Product Hunt'),
  ('Devstral 2', 'huggingface.co', 'devstral-2', 'Product Hunt'),
  ('InsForge', 'insforge.dev', 'insforge-2', 'Product Hunt'),
  ('Raydian', 'raydian.dev', 'raydian', 'Product Hunt'),
  ('The ∞ Bar', 'theinfinite.bar', 'the-bar', 'Product Hunt'),
  ('Baserow 2.0', 'baserow.io', 'baserow-2-0', 'Product Hunt'),
  ('Cumbuca', 'cumbuca.com', 'cumbuca', 'Product Hunt'),
  ('Zo Computer', 'zo.computer', 'zo-computer-2', 'Product Hunt'),
  ('Juice', 'juice.co', 'juice-4', 'Product Hunt'),
  ('AI Toolkit by Tiptap', 'tiptap.dev', 'ai-toolkit-by-tiptap', 'Product Hunt'),
  ('Refbox', 'ref.box', 'refbox', 'Product Hunt'),
  ('Rep by Clarify', 'clarify.ai', 'rep-by-clarify', 'Product Hunt'),
  ('SourcePilot', 'sourcepilot.co', 'sourcepilot', 'Product Hunt'),
  ('Lyria Camera by Google DeepMind', 'magenta.withgoogle.com', 'lyria-camera-by-google-deepmind', 'Product Hunt'),
  ('AI Website Builder by beehiiv', 'beehiiv.com', 'ai-website-builder-by-beehiiv', 'Product Hunt'),
  ('Super V2', 'super.work', 'super-v2', 'Product Hunt'),
  ('CUDA 13.1', 'developer.nvidia.com', 'cuda-13-1', 'Product Hunt'),
  ('Color Palette Pro', 'colorpalette.pro', 'color-palette-pro', 'Product Hunt'),
  ('Formly 2.0', 'getformly.com', 'formly-2-0', 'Product Hunt'),
  ('Browser Buddy', 'browserbuddy.com', 'browser-buddy-2', 'Product Hunt'),
  ('Orca', 'orcaengine.ai', 'orca-135c20d5-18ec-472b-901f-207747d6a036', 'Product Hunt'),
  ('BrowserBook', 'browserbook.com', 'browserbook', 'Product Hunt'),
  ('Contenov', 'contenov.com', 'contenov', 'Product Hunt'),
  ('Magic Mango', 'magicmango.ai', 'magic-mango', 'Product Hunt'),
  ('Comet for Android ', 'perplexity.ai', 'comet-for-android', 'Product Hunt'),
  ('Shipper Advisor', 'shipper.now', 'shipper-advisor', 'Product Hunt'),
  ('Swipe Insider', 'theswipeinsider.com', 'swipe-insider', 'Product Hunt'),
  ('CareerScalar', 'careerscalar.com', 'careerscalar', 'Product Hunt'),
  ('30tools - Free AI Tools for Everything', 'ai-tools.30tools.com', '30tools-free-ai-tools-for-everything', 'Product Hunt'),
  ('StakeLiGames', 'stake-li-games.vercel.app', 'stakeligames', 'Product Hunt'),
  ('Tiinver', 'tiinver.com', 'tiinver', 'Product Hunt'),
  ('Odysy', 'getodysy.com', 'odysy', 'Product Hunt'),
  ('Xermius', 'xermius.com', 'xermius', 'Product Hunt'),
  ('Mail List Shield', 'documenter.getpostman.com', 'mail-list-shield', 'Product Hunt'),
  ('MYNX', 'usemynx.com', 'mynx', 'Product Hunt'),
  ('AppFinito - Your app in 1 day', 'appfinito.com', 'appfinito-your-app-in-1-day', 'Product Hunt'),
  ('LocoMoco', 'home.locomoco.top', 'locomoco', 'Product Hunt'),
  ('SupportRetriever', 'supportretriever.com', 'supportretriever', 'Product Hunt'),
  ('Align: Identity Reprogramming App', 'alignapp.eu', 'align-identity-reprogramming-app', 'Product Hunt'),
  ('The Weekly Patent Law Review', 'complete.city', 'the-weekly-patent-law-review', 'Product Hunt'),
  ('Elastic Email MCP Server', 'elasticemail.com', 'elastic-email-mcp-server-2', 'Product Hunt'),
  ('CarGPT', 'cargptapp.com', 'cargpt', 'Product Hunt'),
  ('VaultNote', 'vaultnote.rishishah.in', 'vaultnote', 'Product Hunt'),
  ('SnapShot', 'getsnapshots.app', 'snapshot-5', 'Product Hunt'),
  ('Wrap by SaaSBillboards', 'wrap.saasbillboards.com', 'wrap-by-saasbillboards', 'Product Hunt'),
  ('Good Vibes Post', 'goodvibespost.online', 'good-vibes-post', 'Product Hunt'),
  ('MetaMagic', 'metamagic.vercel.app', 'metamagic', 'Product Hunt'),
  ('ViteTools.dev', 'vitetools.dev', 'vitetools-dev', 'Product Hunt'),
  ('BotGround', 'botground.xyz', 'botground', 'Product Hunt'),
  ('Raptor', 'raptordata.dev', 'raptor', 'Product Hunt'),
  ('Kanji', 'kanjieight.vercel.app', 'kanji', 'Product Hunt'),
  ('Unstack Pro', 'unstack.pro', 'unstack-pro', 'Product Hunt'),
  ('Trend Radar', 'trendradar.app', 'trend-radar', 'Product Hunt'),
  ('Focus Patrol', 'focuspatrol.bayer.ooo', 'focus-patrol', 'Product Hunt'),
  ('InfiniTalk AI', 'infinitetalkai.com', 'infinitalk-ai', 'Product Hunt'),
  ('StatJam', 'statjam.net', 'statjam', 'Product Hunt'),
  ('Table Read Studio', 'tablereadstudio.app', 'table-read-studio', 'Product Hunt'),
  ('Packet.School', 'packet.school', 'packet-school', 'Product Hunt'),
  ('HCB Mobile', 'hackclub.com', 'hcb-mobile', 'Product Hunt'),
  ('Website Launches API', 'websitelaunches.com', 'website-launches-api', 'Product Hunt'),
  ('XtractAPI 2.0', 'xtractapi.com', 'xtractapi-2-0', 'Product Hunt'),
  ('Narrativee', 'narrativee.com', 'narrativee', 'Product Hunt'),
  ('JSONing Mock API', 'jsoning.com', 'jsoning-mock-api', 'Product Hunt'),
  ('Flow', 'flow.acertine.com', 'flow-1465910f-5028-4010-96c5-ff5b97041ecb', 'Product Hunt'),
  ('Spendless', 'getspendless.com', 'spendless-2', 'Product Hunt'),
  ('Redecora AI', 'redecora.ai', 'redecora-ai', 'Product Hunt'),
  ('Morph-Ai-Era', 'morph-ai-era.online', 'morph-ai-era', 'Product Hunt'),
  ('Famelee.ai', 'famelee.ai', 'famelee-ai', 'Product Hunt'),
  ('Super Agent Stack', 'superagentstack.com', 'super-agent-stack', 'Product Hunt'),
  ('Whisper flow: AI Voice Typing', 'play.google.com', 'whisper-flow-ai-voice-typing', 'Product Hunt'),
  ('Cascade', 'withcascade.com', 'cascade-bf2c7480-d175-46b5-aec2-5052a28089d8', 'Product Hunt'),
  ('Hyde: AI Bullshit Detector', 'hyde.bot', 'hyde-ai-bullshit-detector', 'Product Hunt'),
  ('JavaScript Obfuscator Pro', 'obfuscator.io', 'javascript-obfuscator-pro', 'Product Hunt'),
  ('AeroChat AI Chat for Shopify', 'apps.shopify.com', 'aerochat-ai-chat-for-shopify', 'Product Hunt'),
  ('Alert Lions', 'alertlions.com', 'alert-lions', 'Product Hunt'),
  ('How Crypto Gets Its Price Tag Quiz', 'trendlinegala.com', 'how-crypto-gets-its-price-tag-quiz', 'Product Hunt'),
  ('VTech Service', 'vtechxhub.com', 'vtech-service', 'Product Hunt'),
  ('Better Powerpoints', 'betterpowerpoints.com', 'better-powerpoints', 'Product Hunt'),
  ('AffiliateFinders', 'affiliatefinders.com', 'affiliatefinders', 'Product Hunt')
ON CONFLICT (domain) DO NOTHING;